// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HubStatusResponse = { running: boolean, endpoint: string | null, pid: number | null, startedAt: bigint | null, lanEnabled: boolean, deviceCount: number, reason: string | null, };
